# Generated by Django 4.1.3 on 2022-11-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "placa",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("marca", models.CharField(max_length=65)),
                ("modelo", models.CharField(max_length=65)),
                ("tipo", models.CharField(max_length=45)),
                ("color", models.CharField(max_length=55)),
                ("cc", models.IntegerField(blank=True)),
            ],
        ),
    ]
