# Generated by Django 4.1.3 on 2022-11-24 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0001_initial"),
        ("vehiculo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiculo",
            name="persona",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="persona.persona",
            ),
        ),
    ]
