# Generated by Django 4.1.3 on 2022-11-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehiculo", "0002_vehiculo_persona"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mantenimiento",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.CharField(max_length=85)),
                ("fecha", models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name="vehiculo",
            name="mantenimiento",
            field=models.ManyToManyField(blank=True, to="vehiculo.mantenimiento"),
        ),
    ]
